### ISSUE TITLE
feat: add option to display interactions in their actual order

### ISSUE THREAD

**Issue by asiaziola** [redstone-finance/redstone-sonar#11]
Add option (a switch maybe?) to display interactions in the actual order in which they are processed by the SDK. Gateway returns sorted interactions based on their block height, so there is no guarantee they are sorted correctly when multiple interactions are in the same block (protocol orders them lexicographically).

**Comment by ppedziwiatr** [comment]
DO IT NOW!!!!!!! use the https://github.com/redstone-finance/redstone-sw-gateway/blob/main/src/gateway/router/gatewayRouter.ts#L27 endpoint for now.

**Comment by asiaziola** [comment]
reopening as it should be added also for testnet interactions (waiting for the installation on testnet gateway)
