### ISSUE TITLE
fix: several fixes / changes

### ISSUE THREAD

**Issue by ppedziwiatr** [redstone-finance/redstone-sonar#16]
1. the contract tx id should the first field on the "interactions" view. It should also have an option to copy value
2. the link to bunled tx should be generated as `arweave.net/{txId}`. Only after certain amount of time - a day or two - it can be generated as a link to viewblock
3. add sortKey value to the interaction view

**Comment by asiaziola** [comment]
does p.2 make sense? how come this tx will appear on arweave.net if its package most probably is not yet sent to arweave...

**Comment by asiaziola** [comment]
ok, I guess you wanted somehow to not wait for viewblock to index the tx. However.. following can be found in viewblock https://viewblock.io/arweave/tx/o5Kwb_VYDjo_49vZqvWmxBf-JUwXyskI54B-l7W1n6U but the tx with same id is not visible on arweave.net? https://arweave.net/tx/o5Kwb_VYDjo_49vZqvWmxBf-JUwXyskI54B-l7W1n6U not sure why it is not found...

**Comment by ppedziwiatr** [comment]
> does p.2 make sense? how come this tx will appear on arweave.net if its package most probably is not yet sent to arweave...

It is retrieved from the internal gateway cache - if it's not found in gateway's cache, it fallbacks to Bundlr's cache.
That's why transactions posted to Bundlr are immediately on arweave.net/txId endpoint - even before being mined - they are effectively served by Bundlr's cache.

**Comment by ppedziwiatr** [comment]
> ok, I guess you wanted somehow to not wait for viewblock to index the tx. However.. following can be found in viewblock https://viewblock.io/arweave/tx/o5Kwb_VYDjo_49vZqvWmxBf-JUwXyskI54B-l7W1n6U but the tx with same id is not visible on arweave.net? https://arweave.net/tx/o5Kwb_VYDjo_49vZqvWmxBf-JUwXyskI54B-l7W1n6U not sure why it is not found...

This (`o5Kwb_VYDjo_49vZqvWmxBf-JUwXyskI54B-l7W1n6U`) is a bundled transaction - it won't be available as a separate transaction through arweave.net/tx/{txId} endpoint - only the bundle that it is contained within (ie. `PzmsLIhXVEctlv-aDPz6kjxS9mtPGw7j7NuTTnh7P1s` - https://arweave.net/tx/PzmsLIhXVEctlv-aDPz6kjxS9mtPGw7j7NuTTnh7P1s)
Viewblock "unpacks" all the transactions contained within the bundle - that's why the `o5Kwb_VYDjo_49vZqvWmxBf-JUwXyskI54B-l7W1n6U` is visible there as a separate transaction..yup, that's confusing :-)

Please note that
1. arweave.net/{txId}
2. arweave.net/tx/{txId}

are different endpoints.

**Comment by asiaziola** [comment]
yeah, I'm aware. However following link https://arweave.net/o5Kwb_VYDjo_49vZqvWmxBf-JUwXyskI54B-l7W1n6U (bundled tx id) downloads a strangely encoded document
<img width="704" alt="Screenshot 2022-05-30 at 11 38 22" src="https://user-images.githubusercontent.com/22620416/170964601-838911a8-9a93-4cbd-b297-e930c67588e2.png">

Am I missing sth? :D

**Comment by ppedziwiatr** [comment]
The bundled interactions are gzipped, to reduce the costs...

pon., 30 maj 2022, 11:41 użytkownik Asia ***@***.***> napisał:

**Comment by asiaziola** [comment]
^^ ok, p. 1 and 2 on prod, p. 3 is waiting for this little thing https://github.com/redstone-finance/redstone-sw-gateway/pull/67

**Comment by ppedziwiatr** [comment]
> ^^ ok, p. 1 and 2 on prod, p. 3 is waiting for this little thing [redstone-finance/redstone-sw-gateway#67](https://github.com/redstone-finance/redstone-sw-gateway/pull/67)

deployed
